### ISSUE TITLE
Not writing to BigQuery

### ISSUE THREAD

**Issue by DediBar** [theShadow89/nifi-bigquery-bundle#4]
Hi 
I am consuming JSON from KAFKA with ConsumeKafka_0_11 JSON TOPIC and than transfer it to PutBigquery, I create table and have permissions but I do not see any record in the table.

At NiFi Data Provenance I see only DROP TYPE 

Any Idea how to solve it ?
 
Thank you

**Comment by theShadow89** [comment]
The JSON structure should be the same as the defined Bigquery Schema for your table otherwise, the insertions fails. Have you checked it?

**Comment by DediBar** [comment]
Hi 
Yes it is same JSON as in the test AbstractBigqueryProcessorTest.java
https://github.com/theShadow89/nifi-bigquery-bundle/blob/master/nifi-bigquery-processors/src/test/java/org/apache/nifi/processors/bigquery/AbstractBigqueryProcessorTest.java

**Comment by DediBar** [comment]
The response message have no errors 
Maybe You have test code that I can run from my laptop with My credentials ?
I try to debug it but did not found the issue

**Comment by husnuumus** [comment]
If the json object has any null or empty fields the bigquery schema will not be generated as expected. So I strongly recommend to you compare the bigquery table schema with one of those failed json objects.

Additionally, you can try bigquery python or google scripts api instead of nifi plugin. If the insertion done successfully which means there are some fields which is not represented in the bigquery schema.

**Comment by theShadow89** [comment]
@DediBar the suggestion of @husnuumus is the best test you can take to be sure that there aren't any error on your schema
